--- #YAML:1.0
name: Test-Float
version: 0.10
author: ~
abstract: |-
  Compare if two numbers are equal within a specified precision
license: perl
requires:
  Test::Builder: 0.22
build_requires:
  Test::Builder::Tester: 1.01
  Test::More: 0.53
provides:
  Test::Float:
    file: lib/Test/Float.pm
    version: 0.10
generated_by: Module::Build version 0.2606
